version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: subastup-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SubastUP2026!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql # Esto hace que los datos no se borren si apagás el contenedor

volumes:
  sqlserver-data:

  